const mongoose = require('mongoose');

const ACTIVITY_EVENT_TYPES = [
  'COURSE_CREATED',
  'COURSE_UPDATED',
  'COURSE_PUBLISHED',
  'COURSE_ARCHIVED',
  'COURSE_RESTORED',
  'LESSON_CREATED',
  'LESSON_UPDATED',
  'LESSON_DELETED',
  'ENROLLMENT_CREATED',
  'PROGRESS_UPDATED',
  'COMMENT',
];

const activityLogSchema = new mongoose.Schema(
  {
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: [true, 'Course is required'],
    },
    actorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Actor is required'],
    },
    eventType: {
      type: String,
      enum: ACTIVITY_EVENT_TYPES,
      required: [true, 'Event type is required'],
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
    // This collection is append-only — no UPDATE or DELETE operations.
    // updatedAt is generated by Mongoose but will never change after creation.
  }
);

// Index to fetch the activity feed for a course in reverse chronological order
activityLogSchema.index({ courseId: 1, createdAt: -1 });

module.exports = mongoose.model('ActivityLog', activityLogSchema);
module.exports.ACTIVITY_EVENT_TYPES = ACTIVITY_EVENT_TYPES;
